Feat/implementando backend
alexleandr/invicto-app-frontend pull request #7
Opened 2023-06-06 18:29 UTC by alexleandr

Ajustes de implementação da API no frontend.

2023-06-13 05:32 UTC, CaioVinicius7 requested changes

2023-06-13 05:32 UTC, CaioVinicius7 commented on src/pages/Main/components/ViceCard/index.jsx
> +        if (diff <= 86400) {
Acredito que da pra diminuir isso, para não esquentar a cabeça pergunte ao nosso amigo GPT, ele deve deixar isso um pouco mais curto.

2023-06-13 05:32 UTC, CaioVinicius7 commented on src/pages/Main/components/ViceCard/index.jsx
> +                    {timeDiff !== '' ? (
aqui da para ficar da seguinte maneira:

`!!timeDiff ? <h4>{timeDiff}</h4> : null` ou `!!timeDiff && <h4>{timeDiff}</h4>`

Resumo do que está acontecendo:

Uma string vazia é null no JS, então somente `timeDiff && <h4>{timeDiff}</h4>` porém é interessante sempre usarmos expressões que retornam um boleano em condicionais em vez de coisas que podem ser true ou false (ex: array vazio, string vazia), devido a isso usamos `!!` antes para converter para negação desse valor em booleano e depois converter a negação do valor para o valor original, é meio confuso de inicio, mas olha o exemplo abaixo:

`"" = false` -> string vazia é considerado false

`!"" = true` -> Fazemos a negação ai vira true em boleano

`!!"" = false` -> fazemos a negação da negação ai vira um boleano de vdd, não algo que é considerado true ou false

OBS: sei que ficou meio ruim a explicação, mas caso ainda fique em dúvida é só me perguntar

2023-06-13 05:32 UTC, CaioVinicius7 commented on src/pages/Main/styles.jsx
Um detalhe que percebi nesse aquivo:

O arquivo está com a extensão `jsx`, o correto seria o arquivo ter a extensão `js`, pois utilizamos a extensão jsx somente quando é um arquivo js que retorna html.

2023-06-13 05:32 UTC, CaioVinicius7 commented on src/pages/Main/components/ViceCard/components/DeleteVice/index.jsx
> +    async function deleteVice(userId, viceId, token) {
Aqui tem uma coisa interessante que você pode alterar que vai diminuir o código e deixar as coisas mais simples, em vez de recuperar o token e passar ele nos headers da requisição é mais fácil você fazer isso na função de login do sistema e no useEffect do contexto.

No caso ficaria assim na função de login:

```
      const { token } = await authService.login({
        username,
        password
      });

      localStorage.setItem("token", token);

      api.defaults.headers["Authorization"] = `Bearer ${token}`;
```

E no useEffect do contexto ficaria assim:

```
useEffect(() => {
    const token = localStorage.getItem("token");

    if (token) {
      api.defaults.headers["Authorization"] = `Bearer ${token}`;

      getUserData();
    }
  }, []);
```

OBS: exemplos tirados de um projeto meu, vai precisar alterar algumas coisas, mas da para você entender a ideia olhando e aplicar.

2023-06-13 23:29 UTC, alexleandr commented on src/pages/Main/components/ViceCard/index.jsx
> +        if (diff <= 86400) {
"Apesar de ser possível refatorar o código ainda mais, essa seria uma forma mais legível e fácil de entender as diferentes condições e ações associadas." - Gepetê, Chate

2023-06-13 23:36 UTC, alexleandr commented on src/pages/Main/components/ViceCard/index.jsx
> +                    {timeDiff !== '' ? (
Que massa!! entendi sim a explicação, dei uma pesquisada também. Resolvido.

2023-06-16 03:38 UTC, CaioVinicius7 approved these changes

2023-06-16 03:38 UTC, merged